name: Workflows basics

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3002341@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        env: 
          DEFAULT_BRANCH: main
